### ISSUE TITLE
Assembly4 WB crashes FC

### ISSUE THREAD

**Issue by Anool** [Zolko-123/FreeCAD_Assembly4#39]
Per the tutorial at 
https://github.com/Zolko-123/FreeCAD_Assembly4/blob/master/Examples/Tutorial1/TUTORIAL1.md 
, I created axis and bearing FC files.
In asm_tuto1 , when trying to insert part using Assembly > Link an external Part , FreeCad crashes.
I've tried it on different FC versions : (Appimages as well as Stable installation) Version info appended below.
++++++++++++++++++++++++++++
OS: Ubuntu 18.04.4 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git) AppImage
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 2.7.6
Qt version: 4.8.6
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/India (en_IN)
++++++++++++++++++++++++++++
OS: Ubuntu 18.04.4 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16079 (Git) AppImage
Build type: Release
Branch: master
Hash: 6363c90a20b296ab69d7b52230009928199d90df
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/India (en_IN)
++++++++++++++++++++++++++++
OS: Ubuntu 18.04.4 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4.
Build type: Release
Python version: 3.6.8
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/India (en_IN)
++++++++++++++++++++++++++++

The error log is appended below : 

 freecad
FreeCAD 0.18.4, Libs: 0.18.4R
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Loading Assembly4 WorkBench
Sheet Metal workbench loaded
Enumeration index -1 is out of range, ignore it
Enumeration index -1 is out of range, ignore it
Enumeration index -1 is out of range, ignore it
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7ff0e3db4f20]
#1  0x7ff0e628eeb8 in App::OriginGroupExtension::relinkToOrigin(App::DocumentObject*) from /usr/lib/freecad-python3/lib/libFreeCADApp.so+0x38
#2  0x7ff0e628fc77 in App::OriginGroupExtension::addObjects(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> >) from /usr/lib/freecad-python3/lib/libFreeCADApp.so+0x47
#3  0x7ff0e623cc61 in App::GroupExtension::addObject(App::DocumentObject*) from /usr/lib/freecad-python3/lib/libFreeCADApp.so+0x91
#4  0x7ff0e623c8e9 in App::GroupExtension::addObject(char const*, char const*) from /usr/lib/freecad-python3/lib/libFreeCADApp.so+0x69
#5  0x7ff0e623fcfc in App::GroupExtensionPy::newObject(_object*) from /usr/lib/freecad-python3/lib/libFreeCADApp.so+0x5c
#6  0x7ff0e623fd87 in App::GroupExtensionPy::staticCallback_newObject(_object*, _object*) from /usr/lib/freecad-python3/lib/libFreeCADApp.so+0x37
#7  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyCFunction_FastCallDict+0x1bb) [0x7ff0e58ad77b]
#8  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c44c) [0x7ff0e581644c]
#9  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3) [0x7ff0e581c563]
#10  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17aa63) [0x7ff0e5814a63]
#11  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyFunction_FastCallDict+0x2d5) [0x7ff0e5816085]
#12  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x131) [0x7ff0e5901211]
#13  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyObject_Call_Prepend+0xcd) [0x7ff0e590193d]
#14  /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(PyObject_Call+0x48) [0x7ff0e59019a8]
#15  0x7ff0e1911e52 in PySide::SignalManager::callPythonMetaMethod(QMetaMethod const&, void**, _object*, bool) from /usr/lib/x86_64-linux-gnu/libpyside2.cpython-36m-x86_64-linux-gnu.so.5.11+0x82
#16  0x7ff0e19121c6 in PySide::SignalManager::qt_metacall(QObject*, QMetaObject::Call, int, void**) from /usr/lib/x86_64-linux-gnu/libpyside2.cpython-36m-x86_64-linux-gnu.so.5.11+0x116
#17  0x7ff0e49c1709 in QMetaObject::activate(QObject*, int, int, void**) from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x929
#18  0x7ff0e5098ba2 in QAbstractButton::clicked(bool) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x42
#19  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x245dba) [0x7ff0e5098dba]
#20  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x24719a) [0x7ff0e509a19a]
#21  0x7ff0e509a38d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xfd
#22  /usr/lib/python3/dist-packages/PySide2/QtWidgets.cpython-36m-x86_64-linux-gnu.so(+0x4653cb) [0x7ff0ab9c23cb]
#23  0x7ff0e4fe6048 in QWidget::event(QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1f8
#24  /usr/lib/python3/dist-packages/PySide2/QtWidgets.cpython-36m-x86_64-linux-gnu.so(+0x462553) [0x7ff0ab9bf553]
#25  0x7ff0e4fa783c in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x9c
#26  0x7ff0e4faf65f in QApplication::notify(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7ff
#27  0x7ff0e69a5a98 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x88
#28  0x7ff0e49929c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
#29  0x7ff0e4fae632 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1d2
#30  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1ae16b) [0x7ff0e500116b]
#31  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b07da) [0x7ff0e50037da]
#32  0x7ff0e4fa783c in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x9c
#33  0x7ff0e4faf104 in QApplication::notify(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x2a4
#34  0x7ff0e69a5a98 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x88
#35  0x7ff0e49929c8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x118
#36  0x7ff0e08bc583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x6f3
#37  0x7ff0e08be055 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x135
#38  0x7ff0e08952eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5+0xab
#39  /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x9f260) [0x7ff0d4054260]
#40  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2e7) [0x7ff0dec12417]
#41  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650) [0x7ff0dec12650]
#42  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7ff0dec126dc]
#43  0x7ff0e49eb97f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x5f
#44  0x7ff0e49909fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x13a
#45  0x7ff0e4999aa4 in QCoreApplication::exec() from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5+0x94
#46  0x7ff0e6934fcf in Gui::Application::runApplication() from /usr/lib/freecad-python3/lib/libFreeCADGui.so+0x148f
#47  freecad(main+0x6a2) [0x555764cab5e2]
#48  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7ff0e3d97b97]
#49  freecad(_start+0x2a) [0x555764cac2aa]

++++++++++++++++++++++++++++
![Screenshot from 2020-02-07 00-09-00](https://user-images.githubusercontent.com/760425/73967744-823c2080-493e-11ea-82be-6ca6a1793e5f.png)
++++++++++++++++++++++++++++
![Screenshot from 2020-02-07 00-08-42](https://user-images.githubusercontent.com/760425/73967769-8f590f80-493e-11ea-83d5-860153449c26.png)
++++++++++++++++++++++++++++
![Screenshot from 2020-02-07 00-09-22](https://user-images.githubusercontent.com/760425/73967792-97b14a80-493e-11ea-8877-f5ee9cd5e2ab.png)
++++++++++++++++++++++++++++

**Comment by Anool** [comment]
My bad ! I didn't realize I need FC v0.19 for Assembly 4.
Got the v0.19 Appimage, and Assembly 4 works as expected.
Sorry for the false alarm
