### ISSUE TITLE
Adding fasteners breaks BOM generation

### ISSUE THREAD

**Issue by nullbuilds** [Zolko-123/FreeCAD_Assembly4#454]
Adding a fastener to an assembly and attempting to generate the BOM will result in the following error:
```
21:47:57  ASM4> BOM of the Assembly 4 Model
21:47:57  ASM4> BOM following sub-assemblies
21:47:57  Running the Python command 'Asm4_makeBOM' failed:
Traceback (most recent call last):
  File "C:\Users\Charl\AppData\Roaming\FreeCAD\Mod\Assembly4\.\makeBomCmd.py", line 116, in Activated
    self.listParts(self.model)
  File "C:\Users\Charl\AppData\Roaming\FreeCAD\Mod\Assembly4\.\makeBomCmd.py", line 451, in listParts
    self.listParts(subobj, level+1, parent=obj)
  File "C:\Users\Charl\AppData\Roaming\FreeCAD\Mod\Assembly4\.\makeBomCmd.py", line 381, in listParts
    x_count = obj.NumberX

'FeaturePython' object has no attribute 'NumberX'
```

This was encountered with Assembly4 v0.50.4, Fasteners Workbench 0.4.70, and FreeCAD v0.21.1 (no other workbenches installed).

I've included a minimal example to reproduce the issue; although, as best I can tell this happens to any assembly using a fastener regardless of what else the assembly contains: [BomTest.zip](https://github.com/Zolko-123/FreeCAD_Assembly4/files/13303570/BomTest.zip)

**Comment by Zolko-123** [comment]
BoM is currently quite broken. If you have coding skills and time (and an itch to scratch) you are welcome to improve this
