### ISSUE TITLE
toString() error on array types

### ISSUE THREAD

**Issue by electromuis** [Zolko-123/FreeCAD_Assembly4#490]
When trying to make an array out of a linked part in an assembly and try to save, I get the error:

`
20:36:37  PropertyPythonObject::toString(): failed for <class 'Asm4_objects.ExpressionArray'>
20:36:37  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type FeaturePython is not JSON serializable
20:36:37  PropertyPythonObject::toString(): failed for <class 'Asm4_objects.ViewProviderArray'>
20:36:37  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\FreeCAD 0.21\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type ViewProviderLink is not JSON serializable
`

Freecad version: 0.21.2
Running on commit 83c713e6224b8e34079de784466dc9881b3367ba

(Same error happens to v0.50.7)

**Comment by Zolko-123** [comment]
Yes I see it. It works in 0.21.0 so it's a FreeCAD regression. Let's hope it is fixed in the upcoming 0.21.3

**Comment by Zolko-123** [comment]
I can confirm that this happens on FreeCAD v0.21.2, but works in v0.21.1 and in latest 0.22 weekly build (Version: 0.22.0dev.37573 (Git) AppImage).

I think that it's due to the backport from the 0.22 branch of some bleeding-edge Python 3.11 stuff. 

My advice : use FreeCAD v0.21.1

**Comment by Zolko-123** [comment]
This should be fixed in the latest development branch. Will be in the main branch soon

**Comment by Zolko-123** [comment]
I believe it's fixed now
